package rmq

import (
	"testing"
	"time"

	// TODO: use testify
	. "github.com/adjust/gocheck"
)

func TestCleanerSuite(t *testing.T) {
	TestingSuiteT(&CleanerSuite{}, t)
}

type CleanerSuite struct{}

func (suite *CleanerSuite) TestCleaner(c *C) {
	flushConn, err := OpenConnection("cleaner-flush", "tcp", "localhost:6379", 1)
	c.Check(err, IsNil)
	c.Check(flushConn.flushDb(), IsNil)
	c.Check(flushConn.stopHeartbeat(), IsNil)

	conn, err := OpenConnection("cleaner-conn1", "tcp", "localhost:6379", 1)
	c.Check(err, IsNil)
	queues, err := conn.GetOpenQueues()
	c.Check(err, IsNil)
	c.Check(queues, HasLen, 0)
	queue, err := conn.OpenQueue("q1")
	c.Check(err, IsNil)
	queues, err = conn.GetOpenQueues()
	c.Check(err, IsNil)
	c.Check(queues, HasLen, 1)
	_, err = conn.OpenQueue("q2")
	c.Check(err, IsNil)
	queues, err = conn.GetOpenQueues()
	c.Check(err, IsNil)
	c.Check(queues, HasLen, 2)

	count, err := queue.readyCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(0))
	err = queue.Publish("del1")
	c.Check(err, IsNil)
	count, err = queue.readyCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(1))
	err = queue.Publish("del2")
	c.Check(err, IsNil)
	count, err = queue.readyCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(2))
	err = queue.Publish("del3")
	c.Check(err, IsNil)
	count, err = queue.readyCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(3))
	err = queue.Publish("del4")
	c.Check(err, IsNil)
	count, err = queue.readyCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(4))
	err = queue.Publish("del5")
	c.Check(err, IsNil)
	count, err = queue.readyCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(5))
	err = queue.Publish("del6")
	c.Check(err, IsNil)
	count, err = queue.readyCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(6))

	count, err = queue.unackedCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(0))
	c.Check(queue.StartConsuming(2, time.Millisecond), IsNil)
	time.Sleep(time.Millisecond)
	count, err = queue.unackedCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(2))
	count, err = queue.readyCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(4))

	consumer := NewTestConsumer("c-A")
	consumer.AutoFinish = false
	consumer.AutoAck = false

	_, err = queue.AddConsumer("consumer1", consumer)
	c.Check(err, IsNil)
	time.Sleep(10 * time.Millisecond)
	count, err = queue.unackedCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(2))
	count, err = queue.readyCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(4))

	c.Assert(consumer.LastDelivery, NotNil)
	c.Check(consumer.LastDelivery.Payload(), Equals, "del1")
	err = consumer.LastDelivery.Ack()
	c.Check(err, IsNil)
	time.Sleep(10 * time.Millisecond)
	count, err = queue.unackedCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(2))
	count, err = queue.readyCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(3))

	consumer.Finish()
	time.Sleep(10 * time.Millisecond)
	count, err = queue.unackedCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(2))
	count, err = queue.readyCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(3))
	c.Check(consumer.LastDelivery.Payload(), Equals, "del2")

	queue.StopConsuming()
	c.Check(conn.stopHeartbeat(), IsNil)
	time.Sleep(time.Millisecond)

	conn, err = OpenConnection("cleaner-conn1", "tcp", "localhost:6379", 1)
	c.Check(err, IsNil)
	queue, err = conn.OpenQueue("q1")
	c.Check(err, IsNil)

	err = queue.Publish("del7")
	c.Check(err, IsNil)
	count, err = queue.readyCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(4))
	err = queue.Publish("del8")
	c.Check(err, IsNil)
	count, err = queue.readyCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(5))
	err = queue.Publish("del9")
	c.Check(err, IsNil)
	count, err = queue.readyCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(6))
	err = queue.Publish("del10")
	c.Check(err, IsNil)
	count, err = queue.readyCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(7))
	err = queue.Publish("del11")
	c.Check(err, IsNil)
	count, err = queue.readyCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(8))

	count, err = queue.unackedCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(0))
	c.Check(queue.StartConsuming(2, time.Millisecond), IsNil)
	time.Sleep(time.Millisecond)
	count, err = queue.unackedCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(2))
	count, err = queue.readyCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(6))

	consumer = NewTestConsumer("c-B")
	consumer.AutoFinish = false
	consumer.AutoAck = false

	_, err = queue.AddConsumer("consumer2", consumer)
	c.Check(err, IsNil)
	time.Sleep(10 * time.Millisecond)
	count, err = queue.unackedCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(2))
	count, err = queue.readyCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(6))
	c.Check(consumer.LastDelivery.Payload(), Equals, "del4")

	consumer.Finish() // unacked
	time.Sleep(10 * time.Millisecond)
	count, err = queue.unackedCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(2))
	count, err = queue.readyCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(6))

	c.Check(consumer.LastDelivery.Payload(), Equals, "del5")
	err = consumer.LastDelivery.Ack()
	c.Check(err, IsNil)
	time.Sleep(10 * time.Millisecond)
	count, err = queue.unackedCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(2))
	count, err = queue.readyCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(5))

	queue.StopConsuming()
	c.Check(conn.stopHeartbeat(), IsNil)
	time.Sleep(time.Millisecond)

	cleanerConn, err := OpenConnection("cleaner-conn", "tcp", "localhost:6379", 1)
	c.Check(err, IsNil)
	cleaner := NewCleaner(cleanerConn)
	returned, err := cleaner.Clean()
	c.Check(err, IsNil)
	c.Check(returned, Equals, int64(4))
	count, err = queue.readyCount()
	c.Check(err, IsNil)
	c.Check(count, Equals, int64(9)) // 2 of 11 were acked above
	queues, err = conn.GetOpenQueues()
	c.Check(err, IsNil)
	c.Check(queues, HasLen, 2)

	conn, err = OpenConnection("cleaner-conn1", "tcp", "localhost:6379", 1)
	c.Check(err, IsNil)
	queue, err = conn.OpenQueue("q1")
	c.Check(err, IsNil)
	c.Check(queue.StartConsuming(10, time.Millisecond), IsNil)
	consumer = NewTestConsumer("c-C")

	_, err = queue.AddConsumer("consumer3", consumer)
	c.Check(err, IsNil)
	time.Sleep(10 * time.Millisecond)
	c.Check(consumer.LastDeliveries, HasLen, 9)

	queue.StopConsuming()
	c.Check(conn.stopHeartbeat(), IsNil)
	time.Sleep(time.Millisecond)

	returned, err = cleaner.Clean()
	c.Check(err, IsNil)
	c.Check(returned, Equals, int64(0))
	c.Check(cleanerConn.stopHeartbeat(), IsNil)
}
